language: python
python:
  - 2.7

###
### Add services
###
services:
  - docker


###
### Global variables
###
env:
  global:
    # Get .env default versions
    - VAR=VAL

###
### Berfore Install
###
before_install:
  # List versions
  - docker version
  - docker-compose version

###
### Install
###
install:
  - true



###
### Test
###
script:
  - .tests/test.sh .
